services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        NEXT_PUBLIC_API_URL: http://10.17.34.14:8010
        NEXT_PUBLIC_API_BASE_URL: http://10.17.34.14:8010/api/v1
    ports:
      - "8011:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://10.17.34.14:8010
      - NEXT_PUBLIC_API_BASE_URL=http://10.17.34.14:8010/api/v1
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8010:8000"
    environment:
      POSTGRES_SERVER: host.docker.internal
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: obs_db
      CLICKHOUSE_HOST: host.docker.internal
      CLICKHOUSE_PORT: 8123
      CLICKHOUSE_USER: clickhouse
      CLICKHOUSE_PASSWORD: clickhouse
      CORS_ORIGINS: http://10.17.34.14:8011,http://localhost:8011,http://localhost:3000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    volumes:
      - ./backend/app:/app/app

  # postgres:
  #   image: postgres:15
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: obs_db
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres-data:/var/lib/postgresql/data/
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

  # clickhouse:
  #   image: clickhouse/clickhouse-server:latest
  #   restart: always
  #   environment:
  #     CLICKHOUSE_DB: default
  #     CLICKHOUSE_USER: clickhouse
  #     CLICKHOUSE_PASSWORD: clickhouse
  #   ports:
  #     - "8123:8123"  # HTTP interface
  #     - "9000:9000"  # Native client interface
  #   volumes:
  #     - clickhouse-data:/var/lib/clickhouse/
  #     - ./backend/clickhouse-config.xml:/etc/clickhouse-server/config.d/custom_config.xml:ro # Optional
  #   healthcheck:
  #     test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5


# volumes:
#   postgres-data:
#   clickhouse-data:

